favicon: null
name: "Burg's Blog"
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.375
  rhythmicContrast: 0.4892589
  brandColors:
    - '#765D4C'
    - '#BDDED9'
    - '#0D0504'
    - '#0488C7'
    - '#80C7F1'
  lightness: 0.5
typography_spectrum: 0.08853288
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9962406
analytics:
  twitter: null
  google: UA-74666702-1
  facebook: null
