collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1197637
color:
  saturation: 0.03986207
  brandStrength: 0.4709038
  rhythmicContrast: 0.3761323
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.9154696
layout_spectrum: 0.2669173
name: Burgs Blog
