favicon: null
name: "Burg's Blog"
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.4747049
  lightness: 0.5
  brandColors:
    - '#111B50'
    - '#050A1F'
    - '#C6A100'
    - '#5A192F'
    - '#3B2050'
  rhythmicContrast: 0.4892589
typography_spectrum: 0.08853288
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: UA-74666702-1
  facebook: null
