favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.4873524
  lightness: 0.5
  brandColors:
    - '#DDDDDD'
    - '#3F547F'
    - '#A8ACB8'
    - '#F68835'
    - '#FFFFFF'
  rhythmicContrast: 0.4892589
typography_spectrum: 0.08853288
layout_spectrum: 0.9672395
analytics:
  twitter: null
  google: UA-74666702-1
  facebook: null
name: "Burg's Blog"
